---
--- Generated by Luanalysis
--- Created by drago.
--- DateTime: 2025/5/10 16:23
---

-- 优惠券库存健
local stockKey = KEYS[1]
-- 优惠券下单用户
local stockUser = KEYS[2]

-- 优惠券id
local vocuherId = AGV[1]
-- 用户id
local userId = AGV[2]

-- 判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    return 1
end

-- 判断用户是否已下单
if (redis.call('SISMEMBER', stockUser, userId) == 1) then
    return 2
end

-- 扣减库存，userId存入set集合
redis.call('incrby', stockKey, -1)
redis.call('sadd', stockUser, userId)
return 0


