---
--- Generated by Luanalysis
--- Created by drago.
--- DateTime: 2025/4/5 19:33
---

-- 比较线程标识与redis中的锁标识是否一致
if (redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0